import "./globals.css"; // Asegura que esta ruta a globals.css sea correcta
import { ClerkProvider } from '@clerk/nextjs'; // Importa ClerkProvider

export const metadata = {
  title: "Clerk App", // Puedes cambiar el título aquí
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <main>{children}</main> {/* Esto ayuda con accesibilidad */}
        </body>
      </html>
    </ClerkProvider>
  );
}
